<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A996OJH" failures="1" tests="4" name="Test" time="37.87" errors="0" timestamp="2022-07-16T17:22:35 IST">
  <testcase classname="com.purnadata.testcases.PaymentSummaryTest" name="verifyPurchaseInvoiceExportTest" time="2.301">
    <failure type="java.lang.AssertionError" message="expected [Downloading is successfull] but found [This page isn’t working]">
      <![CDATA[java.lang.AssertionError: expected [Downloading is successfull] but found [This page isn’t working]
at com.purnadata.testcases.PaymentSummaryTest.verifyPurchaseInvoiceExportTest(PaymentSummaryTest.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyPurchaseInvoiceExportTest -->
  <testcase classname="com.purnadata.testcases.PurchaseTest" name="editPurchaseOrder" time="1.789"/>
  <testcase classname="com.purnadata.testcases.CustomerTest" name="verifyCreateCustomerSuccessTest" time="3.326"/>
  <testcase classname="com.purnadata.testcases.CustomerTest" name="verifyCreateCustomerSuccessTest" time="3.511"/>
</testsuite> <!-- Test -->
